# ASSISTments Data Mining Competition 2017 - Optional Semester Project

## Imports and constants

In [1]:
# Imports
import numpy as np
import pandas as pd
import functools
import tensorflow as tf
from sklearn import preprocessing

# Constants
DATA_DIR = 'Data/'

## Loading the data

We load all the data into dataframes

In [2]:
student_train_logs = pd.read_pickle('student_train_logs')
student_test_logs = pd.read_pickle('student_test_logs')

In [3]:
train_idx = student_train_logs['ITEST_id'].unique()

We load the training labels into a dataframe

In [4]:
train_labels = pd.read_csv('Data/training_label.csv', index_col='ITEST_id').sort_index()
train_labels.drop_duplicates(subset=None, keep='first', inplace=True)

In [5]:
STEM_idx = train_labels[train_labels['isSTEM'] == 1].index.unique()
non_STEM_idx = train_labels[train_labels['isSTEM'] == 0].index.unique()[:len(STEM_idx)]

print('STEM examples: ', len(STEM_idx))
print('Non STEM examples:', len(non_STEM_idx))

STEM examples:  117
Non STEM examples: 117


## Feature engineering

### Train input data

In order to use an RNN (LSTM), we need to create sequences of actions. A sequence is a matrix in which each row is an action taken by a student that follows a chronological order. An action is a row in the provided dataset (see above). In summary, we produce a Tensor (a 3D array) with the following dimensions:

* First: All the students actions
* Second: A list of actions for a specific student
* Third: A specific action (which in turn is a vector of metrics (see above))

The output that interests us is the last output of the sequence. Which is the output consisting of the last action of a specific student taking into account all previous actions of that student. This output will represent if the student will choose a STEM career or not.

**A problem that we will encounter and will need to solve is that sequences have dynamic lengths**. Because Tensors need to be of fixed predefined size. Meaning that not all students have done the same number of actions while learning.

A possible solution could be to use *padding*. Padding means normalizing the size of all sequences (to the maximum of all sequences size) and add 0 vectors for sequences that are smaller than the maximum size.

In [6]:
# Creation of the input tensor
train_input = []

for idx in STEM_idx:
    specific_student_actions = student_train_logs[student_train_logs['ITEST_id'] == idx]
    student_actions = []
    
    for action_idx, action in specific_student_actions.iterrows():
        student_actions.append(np.array(action))
    
    train_input.append(np.array(student_actions))

for idx in non_STEM_idx:
    specific_student_actions = student_train_logs[student_train_logs['ITEST_id'] == idx]
    student_actions = []
    
    for action_idx, action in specific_student_actions.iterrows():
        student_actions.append(np.array(action))
    
    train_input.append(np.array(student_actions))

In [7]:
len(train_input)

234

For example, first student has taken 504 actions while the second student has taken 129 actions.

We retrieve the biggest sequence and increase the size of all other sequences to be equal to the maximum with 0 vectors

In [8]:
max_sequence_size = 0
for i in range(len(train_input)):
    max_sequence_size = max(max_sequence_size, len(train_input[i]))
max_sequence_size

1863

In [9]:
train_input_padd = []
n_features = len(train_input[0][0])

for i in range(len(train_input)):
    n = len(train_input[i])
    rem = max_sequence_size - n

    z = np.zeros((rem, n_features), dtype=train_input[i].dtype)
    train_input_padd.append(np.concatenate((train_input[i], z)))

In [10]:
train_input_padd[0].shape

(1863, 65)

In [11]:
from random import shuffle
shuffle(train_input_padd)

### Train output data

The training output is a list of one-hot vectors of size 2 (one for each student). If the value of index 0 is 1, then it is non-STEM, if value at index 1 is 1, then it is STEM.

In [12]:
train_output = []

for seq in train_input_padd:
    idx = int(seq[0][0])
    temp_arr = ([0] * 2)
    
    if train_labels.loc[idx]['isSTEM'] == 1:
        temp_arr[1] = 1
    else:
        temp_arr[0] = 1

    train_output.append(temp_arr)

In [13]:
train_output

[[0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 

In [14]:
np.sum(train_output, axis=0)

array([117, 117])

### Test data

We will split the training data into two sets, one for training and the other for testing. We will randomly take 10% of the data for testing and use the rest as training data. Ultimately we will train with everything before predicting.

**TODO** Améliorer ça et utiliser kFold cross validation (stratified), parce qu'on a relativement peu de données

In [15]:
NUM_TEST = int(np.ceil(len(train_input_padd) * 0.1))
print(NUM_TEST)
X_train = train_input_padd[NUM_TEST:]
y_train = train_output[NUM_TEST:]
X_test = train_input_padd[:NUM_TEST]
y_test = train_output[:NUM_TEST]

24


In [16]:
print('Number of students for training:', len(X_train))
print('Number of students for testing:', len(X_test))

Number of students for training: 210
Number of students for testing: 24


## Neural network implementation

Here we fist create placeholders to hold our data. The dimensions for data are [Batch Size, Sequence Length, Input Dimension]. Here our values are:

* Batch size: to be defined at runtime
* Sequence length: Different for each student
* Input Dimension: Known (number of features of the data)

In [17]:
def lazy_property(function):
    attribute = '_' + function.__name__

    @property
    @functools.wraps(function)
    def wrapper(self):
        if not hasattr(self, attribute):
            setattr(self, attribute, function(self))
        return getattr(self, attribute)
    return wrapper


class VariableSequenceClassification:

    def __init__(self, data, target, num_hidden=200, num_layers=2):
        self.data = data
        self.target = target
        self._num_hidden = num_hidden
        self._num_layers = num_layers
        self.prediction
        self.error
        self.optimize

    @lazy_property
    def length(self):
        used = tf.sign(tf.reduce_max(tf.abs(self.data), reduction_indices=2))
        length = tf.reduce_sum(used, reduction_indices=1)
        length = tf.cast(length, tf.int32)
        return length

    @lazy_property
    def prediction(self):
        # Recurrent network.
        output, _ = tf.nn.dynamic_rnn(
            tf.nn.rnn_cell.LSTMCell(self._num_hidden),
            data,
            dtype=tf.float32,
            sequence_length=self.length,
        )
        last = self._last_relevant(output, self.length)
        # Softmax layer.
        weight, bias = self._weight_and_bias(
            self._num_hidden, int(self.target.get_shape()[1]))
        prediction = tf.nn.softmax(tf.matmul(last, weight) + bias)
        return prediction

    @lazy_property
    def cost(self):
        cross_entropy = -tf.reduce_sum(self.target * tf.log(self.prediction))
        return cross_entropy

    @lazy_property
    def optimize(self):
        learning_rate = 0.003
        optimizer = tf.train.AdamOptimizer(learning_rate)
        return optimizer.minimize(self.cost)

    @lazy_property
    def error(self):
        mistakes = tf.not_equal(
            tf.argmax(self.target, 1), tf.argmax(self.prediction, 1))
        return tf.reduce_mean(tf.cast(mistakes, tf.float32))

    @staticmethod
    def _weight_and_bias(in_size, out_size):
        weight = tf.truncated_normal([in_size, out_size], stddev=0.01)
        bias = tf.constant(0.1, shape=[out_size])
        return tf.Variable(weight), tf.Variable(bias)

    @staticmethod
    def _last_relevant(output, length):
        batch_size = tf.shape(output)[0]
        max_length = int(output.get_shape()[1])
        output_size = int(output.get_shape()[2])
        index = tf.range(0, batch_size) * max_length + (length - 1)
        flat = tf.reshape(output, [-1, output_size])
        relevant = tf.gather(flat, index)
        return relevant

## Flow execution

We execute the flow execution graph defined before with our data

In [18]:
y_test

[[0, 1],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [1, 0],
 [0, 1],
 [0, 1],
 [0, 1],
 [0, 1],
 [1, 0],
 [1, 0],
 [0, 1],
 [1, 0],
 [1, 0],
 [1, 0],
 [0, 1],
 [0, 1]]

In [19]:
num_classes = 2
row_size = n_features
batch_size = 10
no_of_batches = int(len(X_train) / batch_size)

data = tf.placeholder(tf.float32, [None, max_sequence_size, row_size])
target = tf.placeholder(tf.float32, [None, num_classes])
model = VariableSequenceClassification(data, target)
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(10):
    ptr = 0
    for _ in range(no_of_batches):
        inp, out = X_train[ptr:ptr+batch_size], y_train[ptr:ptr+batch_size]
        ptr += batch_size
        sess.run(model.optimize, {data: inp, target: out})
    error = sess.run(model.error, {data: X_test, target: y_test})
    print('Epoch {:2d} error {:3.1f}%'.format(epoch + 1, 100 * error))
    print(sess.run(model.prediction,{data: X_test}))

/home/dario/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "


Epoch  1 error 58.3%
[[ 0.61884224  0.38115776]
 [ 0.50725293  0.49274707]
 [ 0.63659924  0.36340079]
 [ 0.61313146  0.38686851]
 [ 0.59237832  0.40762165]
 [ 0.50403124  0.49596879]
 [ 0.50708944  0.4929105 ]
 [ 0.60483438  0.39516565]
 [ 0.62057585  0.37942415]
 [ 0.48670915  0.51329082]
 [ 0.59386724  0.40613276]
 [ 0.59347314  0.40652686]
 [ 0.63674545  0.36325455]
 [ 0.60468924  0.39531073]
 [ 0.58008736  0.41991264]
 [ 0.5195145   0.48048553]
 [ 0.60265648  0.39734346]
 [ 0.60808873  0.39191124]
 [ 0.50403154  0.49596849]
 [ 0.60262519  0.39737484]
 [ 0.62036568  0.37963432]
 [ 0.52715552  0.47284445]
 [ 0.62966353  0.37033647]
 [ 0.50403124  0.49596879]]
Epoch  2 error 50.0%
[[ 0.53961819  0.46038184]
 [ 0.52664393  0.47335601]
 [ 0.58309859  0.41690141]
 [ 0.5294742   0.4705258 ]
 [ 0.51410526  0.4858948 ]
 [ 0.52253836  0.4774617 ]
 [ 0.44178578  0.55821425]
 [ 0.51370549  0.48629457]
 [ 0.54670769  0.45329231]
 [ 0.46166682  0.53833318]
 [ 0.49947566  0.50052434]
 [ 0.5085731